<a href="https://colab.research.google.com/github/bharadwaj103/Aiml-Lab/blob/main/Lab_Exercise_(part2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
input=[1,2,3]
weights=[0.2,0.3,-0.5]
bias=2
output=input[0]*weights[0]+input[1]*weights[1]+input[2]*weights[2]+bias
print(output)

1.3


In [15]:
inputs=[0.4,0.3,1,0.8]
weights1=[0.3,0.2,0.1,0.4]
bias1=0.5
y1=inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1
weights2=[0.4,0.1,-0.1,0.2]
bias2=0.3
y2=inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2
weights3=[0.2,-0.2,-0.1,0.8]
bias3=0.6
y3=inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3
print([y1,y2,y3])

[1.1, 0.55, 1.1600000000000001]


In [21]:
import numpy as np
inputs = np.array([0.4,0.3,1,0.8])
weights = np.array([
    [0.3,0.2,0.1,0.4],
    [0.4,0.1,-0.1,0.2],
    [0.2,-0.2,-0.1,0.8]
])
biases = np.array([0.5,0.3,0.6])
output = np.dot(weights,inputs)+biases
print(output)

[1.1  0.55 1.16]


In [27]:
#Single layer of neurons with activation function

import numpy as np

def relu(x):
  return np.maximum(0,x)

inputs = np.array([0.4, 0.3, 1, 0.8])
weights = np.array([
    [0.3, 0.2, 0.1, 0.4],
    [0.4, 0.1, -0.1, 0.2],
    [0.2, -0.2, -0.1, 0.8]
])
biases = np.array([0.5, 0.3, 0.6])

output = relu(np.dot(weights, inputs) + biases)
#Activation ReLU activation function
output=relu(output)
print(output)


[1.1  0.55 1.16]


In [29]:
import numpy as np

def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def relu(x):
  return np.maximum(0,x)

inputs = np.array([0.4, 0.3, 1, 0.8])
weights = np.array([
    [0.3, 0.2, 0.1, 0.4],
    [0.4, 0.1, -0.1, 0.2],
    [0.2, -0.2, -0.1, 0.8]
])
biases = np.array([0.5, 0.3, 0.6])

output = relu(np.dot(weights, inputs) + biases)
#Activation ReLU activation function
output1=relu(output)
print(output1)
output2=sigmoid(output)
print(output2)



[1.1  0.55 1.16]
[0.75026011 0.63413559 0.76133271]
